apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profile-service-ingress
  namespace: auth-platform
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/profiles
            pathType: Prefix
            backend:
              service:
                name: profile-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profile-service-health-ingress
  namespace: auth-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/actuator/health
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /health/profiles
            pathType: Exact
            backend:
              service:
                name: profile-service
                port:
                  number: 8080
