"""
A2A Tools - Agent-to-Agent Communication Tools

Provides tools for inter-agent communication via A2A protocol.
"""
import json
import logging
import os
from typing import Optional

import httpx
from strands import tool

from shared.config import get_config

logger = logging.getLogger(__name__)


@tool
def invoke_validator_agent(
    task_id: str,
    resource_arn: str,
    resource_type: str,
    control_id: str,
    finding_id: str,
    generated_code: str,
    execution_result: dict,
    memory_session_id: str,
    actor_id: str,
    is_rollback: bool = False
) -> dict:
    """Through A2A protocol, invoke Validator Agent for code review and result verification.

    After Remediator completes code execution, call Validator Agent to:
    1. Review generated code for security issues
    2. Verify execution results
    3. Update Security Hub Finding status
    4. Save experience to LTM
    5. Trigger result email (with rollback link for normal remediation)

    Args:
        task_id: Task ID
        resource_arn: Resource ARN
        resource_type: Resource type (e.g., AwsS3Bucket)
        control_id: Security Hub Control ID (e.g., S3.8)
        finding_id: Security Hub Finding ID
        generated_code: The Python code generated by Remediator
        execution_result: Code execution result from execute_code tool
        memory_session_id: Memory Session ID for context sharing
        actor_id: Actor ID for Memory operations
        is_rollback: Whether this is a rollback operation (rollback emails don't have rollback link)

    Returns:
        dict: Validator Agent response including:
            - success: bool - Whether A2A call succeeded
            - code_review: dict - Code security review results
            - verification: dict - Execution result verification
            - security_hub_update: dict - Security Hub update status
            - experience_saved: dict - LTM save status
            - result_email: dict - Email send status
            - error: str - Error message if failed
    """
    config = get_config()

    # Get Validator Runtime URL from environment
    validator_url = os.environ.get('VALIDATOR_RUNTIME_URL')
    if not validator_url:
        logger.error("VALIDATOR_RUNTIME_URL environment variable not configured")
        return {
            "success": False,
            "error": "VALIDATOR_RUNTIME_URL not configured. Cannot invoke Validator Agent."
        }

    # Build A2A request payload
    # Using direct invocation format instead of JSON-RPC for simplicity with AgentCore Runtime
    a2a_payload = {
        "task_id": task_id,
        "resource_arn": resource_arn,
        "resource_type": resource_type,
        "control_id": control_id,
        "finding_id": finding_id,
        "generated_code": generated_code,
        "execution_result": execution_result,
        "memory_session_id": memory_session_id,
        "memory_id": config.memory_id,
        "actor_id": actor_id,
        "is_rollback": is_rollback
    }

    logger.info(f"Invoking Validator Agent via A2A for task {task_id}")
    logger.info(f"Validator URL: {validator_url}")
    logger.info(f"is_rollback: {is_rollback}")

    try:
        # Make A2A call to Validator runtime
        # Using /invocations endpoint which is the standard AgentCore Runtime endpoint
        with httpx.Client(timeout=300.0) as client:
            response = client.post(
                f"{validator_url}/invocations",
                json=a2a_payload,
                headers={
                    "Content-Type": "application/json",
                    "X-A2A-Source": "remediator-agent",
                    "X-Task-Id": task_id
                }
            )
            response.raise_for_status()

            result = response.json()
            logger.info(f"Validator Agent response received for task {task_id}")

            return {
                "success": True,
                "validator_response": result
            }

    except httpx.TimeoutException as e:
        logger.error(f"A2A call to Validator timed out: {e}")
        return {
            "success": False,
            "error": f"Validator Agent call timed out after 300 seconds"
        }

    except httpx.HTTPStatusError as e:
        logger.error(f"A2A call to Validator failed with HTTP error: {e}")
        return {
            "success": False,
            "error": f"HTTP error {e.response.status_code}: {e.response.text}"
        }

    except Exception as e:
        logger.exception(f"A2A call to Validator failed: {e}")
        return {
            "success": False,
            "error": f"Failed to invoke Validator Agent: {str(e)}"
        }
