"""
Validator Tools - Code Security Review and Result Email Tools

Tools specific to Validator Agent's enhanced responsibilities:
1. Code security review - Check generated code for security risks
2. Result email trigger - Send result email via Lambda
"""
import json
import logging
import os
import re
from typing import Optional

import boto3
from botocore.exceptions import ClientError
from strands import tool

from shared.config import get_config

logger = logging.getLogger(__name__)


@tool
def review_code_security(code: str) -> dict:
    """Review generated code for security risks.

    Analyze the remediation code generated by Remediator Agent for:
    - Dangerous operations (delete, destroy, terminate)
    - Sensitive information leakage (hardcoded credentials)
    - Privilege escalation risks
    - Environment damage potential

    Args:
        code: The Python code to review

    Returns:
        dict: Code review results including:
            - status: str - "passed", "warning", or "rejected"
            - issues: list - List of security issues found
            - risk_level: str - "low", "medium", or "high"
            - recommendations: list - Security recommendations
    """
    issues = []
    recommendations = []
    risk_level = "low"

    logger.info(f"Reviewing code security (code length: {len(code)} chars)")

    # === Dangerous Operation Detection ===
    dangerous_patterns = [
        # Destructive operations
        (r'\.delete_bucket\s*\(', "Detected S3 bucket deletion operation", "high"),
        (r'\.delete_objects\s*\(', "Detected S3 objects deletion operation", "medium"),
        (r'\.terminate_instances\s*\(', "Detected EC2 instance termination", "high"),
        (r'\.delete_security_group\s*\(', "Detected security group deletion", "high"),
        (r'\.delete_db_instance\s*\(', "Detected RDS instance deletion", "high"),
        (r'\.delete_table\s*\(', "Detected DynamoDB table deletion", "high"),
        (r'\.delete_function\s*\(', "Detected Lambda function deletion", "high"),

        # IAM dangerous operations
        (r'iam\.create_user\s*\(', "Detected IAM user creation", "high"),
        (r'iam\.create_access_key\s*\(', "Detected access key creation", "high"),
        (r'iam\.attach_user_policy\s*\(', "Detected user policy attachment", "medium"),
        (r'iam\.put_user_policy\s*\(', "Detected inline user policy creation", "medium"),
        (r'iam\.delete_role\s*\(', "Detected IAM role deletion", "high"),

        # Privilege escalation
        (r'sts\.assume_role\s*\(', "Detected role assumption - verify legitimacy", "medium"),
        (r'AdministratorAccess', "Reference to AdministratorAccess policy", "high"),
        (r'PowerUserAccess', "Reference to PowerUserAccess policy", "medium"),

        # Network security
        (r'0\.0\.0\.0/0', "Detected open CIDR block (0.0.0.0/0)", "medium"),
        (r'::/0', "Detected open IPv6 CIDR block (::/0)", "medium"),
    ]

    for pattern, message, severity in dangerous_patterns:
        if re.search(pattern, code, re.IGNORECASE):
            issues.append({
                "type": "dangerous_operation",
                "message": message,
                "severity": severity
            })
            if severity == "high":
                risk_level = "high"
            elif severity == "medium" and risk_level != "high":
                risk_level = "medium"

    # === Sensitive Information Detection ===
    sensitive_patterns = [
        # Hardcoded credentials
        (r'password\s*=\s*["\'][^"\']{8,}["\']', "Hardcoded password detected"),
        (r'secret\s*=\s*["\'][^"\']{8,}["\']', "Hardcoded secret detected"),
        (r'api_key\s*=\s*["\'][^"\']{8,}["\']', "Hardcoded API key detected"),
        (r'token\s*=\s*["\'][^"\']{20,}["\']', "Hardcoded token detected"),

        # AWS credentials
        (r'AKIA[0-9A-Z]{16}', "AWS Access Key ID detected in code"),
        (r'["\'][A-Za-z0-9/+=]{40}["\']', "Potential AWS Secret Key detected"),

        # Private keys
        (r'-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----', "Private key detected in code"),
        (r'-----BEGIN\s+EC\s+PRIVATE\s+KEY-----', "EC private key detected in code"),
    ]

    for pattern, message in sensitive_patterns:
        if re.search(pattern, code, re.IGNORECASE):
            issues.append({
                "type": "sensitive_info",
                "message": message,
                "severity": "high"
            })
            risk_level = "high"
            recommendations.append("Remove hardcoded credentials and use AWS Secrets Manager or environment variables")

    # === Code Quality Checks ===
    quality_patterns = [
        # Missing error handling
        (r'except\s*:', "Bare except clause - may catch unexpected errors", "low"),
        (r'pass\s*$', "Empty pass statement in except block", "low"),

        # Unsafe practices
        (r'eval\s*\(', "Use of eval() function - potential code injection", "high"),
        (r'exec\s*\(', "Use of exec() function - potential code injection", "high"),
        (r'subprocess\.call\s*\([^)]*shell\s*=\s*True', "Shell=True in subprocess - command injection risk", "high"),
    ]

    for pattern, message, severity in quality_patterns:
        if re.search(pattern, code, re.MULTILINE):
            issues.append({
                "type": "code_quality",
                "message": message,
                "severity": severity
            })
            if severity == "high":
                risk_level = "high"

    # === Determine final status ===
    high_severity_count = sum(1 for i in issues if i.get("severity") == "high")
    medium_severity_count = sum(1 for i in issues if i.get("severity") == "medium")

    if high_severity_count > 0:
        status = "rejected"
        recommendations.append("Review and fix all high-severity issues before execution")
    elif medium_severity_count > 2:
        status = "warning"
        recommendations.append("Consider reviewing medium-severity issues")
    elif issues:
        status = "warning"
    else:
        status = "passed"
        recommendations.append("Code passed security review")

    result = {
        "status": status,
        "issues": issues,
        "risk_level": risk_level,
        "recommendations": recommendations,
        "summary": {
            "total_issues": len(issues),
            "high_severity": high_severity_count,
            "medium_severity": medium_severity_count,
            "low_severity": sum(1 for i in issues if i.get("severity") == "low")
        }
    }

    logger.info(f"Code review completed: status={status}, risk_level={risk_level}, issues={len(issues)}")
    return result


@tool
def trigger_result_email(
    task_id: str,
    resource_arn: str,
    control_id: str,
    code_review_result: dict,
    validation_result: dict,
    is_rollback: bool = False,
    rollback_failed: bool = False,
    error_message: Optional[str] = None
) -> dict:
    """Trigger email service to send result email.

    After Validator completes verification, invoke email service to send
    result email to user. The email includes:
    - Code review results
    - Validation results
    - Rollback link (for normal remediation only, not for rollback operations)

    Supports two modes:
    - HTTP mode (local): Calls EMAIL_SERVICE_URL (e.g., http://email:8080/send)
    - Lambda mode (AWS): Invokes RESULT_EMAIL_LAMBDA_ARN or APPROVAL_HANDLER_ARN

    Args:
        task_id: Task ID
        resource_arn: Resource ARN
        control_id: Security Hub Control ID
        code_review_result: Results from review_code_security tool
        validation_result: Results from verify_resource_state tool
        is_rollback: Whether this is a rollback operation (no rollback link in email)
        rollback_failed: Whether the rollback operation failed
        error_message: Error message to include if operation failed

    Returns:
        dict: Email trigger result including:
            - success: bool - Whether email service was invoked successfully
            - sent: bool - Whether email will be sent
            - includes_rollback_link: bool - Whether email has rollback link
            - error: str - Error message if failed
    """
    config = get_config()

    # Determine email type and content
    if is_rollback:
        if rollback_failed:
            email_type = "rollback_failed"
        else:
            email_type = "rollback_success"
        include_rollback_link = False
    else:
        email_type = "remediation_result"
        include_rollback_link = True

    # Build email payload
    payload = {
        "action": "send_result_email",
        "task_id": task_id,
        "resource_arn": resource_arn,
        "control_id": control_id,
        "email_type": email_type,
        "code_review": {
            "status": code_review_result.get("status", "unknown"),
            "issues_count": code_review_result.get("summary", {}).get("total_issues", 0),
            "risk_level": code_review_result.get("risk_level", "unknown")
        },
        "validation": {
            "passed": validation_result.get("passed", False),
            "checks_count": len(validation_result.get("checks", []))
        },
        "include_rollback_link": include_rollback_link,
        "is_rollback": is_rollback,
        "rollback_failed": rollback_failed,
        "error_message": error_message
    }

    logger.info(f"Triggering result email for task {task_id}")
    logger.info(f"Email type: {email_type}, include_rollback_link: {include_rollback_link}")

    # 获取 Lambda ARN（通过 approval-handler Lambda 发邮件）
    approval_handler_arn = os.environ.get('APPROVAL_HANDLER_ARN')

    if not approval_handler_arn:
        logger.warning("APPROVAL_HANDLER_ARN 未配置")
        return {
            "success": True,
            "sent": False,
            "includes_rollback_link": include_rollback_link,
            "email_type": email_type,
            "message": "邮件 Lambda 未配置（测试环境预期行为）"
        }

    return _send_email_lambda(approval_handler_arn, payload, config.region, include_rollback_link, email_type)


def _send_email_lambda(
    lambda_arn: str,
    payload: dict,
    region: str,
    include_rollback_link: bool,
    email_type: str
) -> dict:
    """通过 Lambda 发送邮件（AWS 部署模式）"""
    try:
        lambda_client = boto3.client('lambda', region_name=region)

        response = lambda_client.invoke(
            FunctionName=lambda_arn,
            InvocationType='Event',  # Async invocation
            Payload=json.dumps(payload)
        )

        status_code = response.get('StatusCode', 0)
        success = status_code in [200, 202]

        logger.info(f"Lambda invocation response: StatusCode={status_code}")

        return {
            "success": success,
            "sent": success,
            "includes_rollback_link": include_rollback_link,
            "email_type": email_type,
            "lambda_status_code": status_code
        }

    except ClientError as e:
        logger.error(f"Failed to invoke result email Lambda: {e}")
        return {
            "success": False,
            "error": f"Lambda invocation failed: {str(e)}"
        }

    except Exception as e:
        logger.exception(f"Error triggering result email: {e}")
        return {
            "success": False,
            "error": f"Failed to trigger result email: {str(e)}"
        }
