"""
Validator Tools - Code Security Review and Result Email Tools

Tools specific to Validator Agent's enhanced responsibilities:
1. Code security review - Check generated code for security risks
2. Result email trigger - Send result email via Lambda
"""
import json
import logging
import os
import re
from typing import Optional

import boto3
from botocore.exceptions import ClientError
from strands import tool

from shared.config import get_config

logger = logging.getLogger(__name__)


def _strip_comments_and_docstrings(code: str) -> str:
    """移除代码中的注释和文档字符串，只保留实际执行的代码。

    Args:
        code: Python 代码

    Returns:
        str: 移除注释和文档字符串后的代码
    """
    # 移除多行文档字符串 ("""...""" 或 '''...''')
    code = re.sub(r'"""[\s\S]*?"""', '', code)
    code = re.sub(r"'''[\s\S]*?'''", '', code)

    # 移除单行注释 (# ...)
    code = re.sub(r'#.*$', '', code, flags=re.MULTILINE)

    return code


def _is_safe_cidr_context(code: str, cidr_pattern: str) -> bool:
    """检查 CIDR 模式是否在安全的上下文中使用。

    安全上下文包括:
    - revoke_security_group_ingress/egress (移除规则 - 安全)
    - 只出现在注释/文档字符串中

    危险上下文:
    - authorize_security_group_ingress/egress (添加规则 - 危险)

    Args:
        code: 完整的代码
        cidr_pattern: CIDR 模式 (如 "0.0.0.0/0")

    Returns:
        bool: True 如果是安全上下文，False 如果是危险上下文
    """
    # 移除注释和文档字符串后的代码
    executable_code = _strip_comments_and_docstrings(code)

    # 如果 CIDR 只出现在注释/文档中，不在可执行代码中，则安全
    if cidr_pattern not in executable_code:
        return True

    # 检查是否在 revoke 操作中（移除规则 - 安全操作）
    # revoke 操作是安全的，因为是在移除开放的 CIDR
    has_revoke = bool(re.search(r'revoke_security_group_(ingress|egress)', executable_code))

    # 检查是否在 authorize 操作中（添加规则 - 危险操作）
    has_authorize = bool(re.search(r'authorize_security_group_(ingress|egress)', executable_code))

    # 如果只有 revoke 没有 authorize，则是安全操作
    if has_revoke and not has_authorize:
        return True

    # 如果有 authorize 操作且 CIDR 在可执行代码中，则危险
    if has_authorize:
        return False

    # 其他情况（如 describe 操作等），视为安全
    return True


@tool
def review_code_security(code: str) -> dict:
    """Review generated code for security risks.

    Analyze the remediation code generated by Remediator Agent for:
    - Dangerous operations (delete, destroy, terminate)
    - Sensitive information leakage (hardcoded credentials)
    - Privilege escalation risks
    - Environment damage potential

    Context-aware analysis:
    - CIDR blocks (0.0.0.0/0) in revoke operations are safe (removing open access)
    - CIDR blocks in authorize operations are dangerous (adding open access)
    - Patterns in comments/docstrings are ignored

    Args:
        code: The Python code to review

    Returns:
        dict: Code review results including:
            - status: str - "passed", "warning", or "rejected"
            - issues: list - List of security issues found
            - risk_level: str - "low", "medium", or "high"
            - recommendations: list - Security recommendations
    """
    issues = []
    recommendations = []
    risk_level = "low"

    logger.info(f"Reviewing code security (code length: {len(code)} chars)")

    # 预处理：获取移除注释后的可执行代码（用于某些检测）
    executable_code = _strip_comments_and_docstrings(code)

    # === Dangerous Operation Detection ===
    dangerous_patterns = [
        # Destructive operations
        (r'\.delete_bucket\s*\(', "Detected S3 bucket deletion operation", "high"),
        (r'\.delete_objects\s*\(', "Detected S3 objects deletion operation", "medium"),
        (r'\.terminate_instances\s*\(', "Detected EC2 instance termination", "high"),
        (r'\.delete_security_group\s*\(', "Detected security group deletion", "high"),
        (r'\.delete_db_instance\s*\(', "Detected RDS instance deletion", "high"),
        (r'\.delete_table\s*\(', "Detected DynamoDB table deletion", "high"),
        (r'\.delete_function\s*\(', "Detected Lambda function deletion", "high"),

        # IAM dangerous operations
        (r'iam\.create_user\s*\(', "Detected IAM user creation", "high"),
        (r'iam\.create_access_key\s*\(', "Detected access key creation", "high"),
        (r'iam\.attach_user_policy\s*\(', "Detected user policy attachment", "medium"),
        (r'iam\.put_user_policy\s*\(', "Detected inline user policy creation", "medium"),
        (r'iam\.delete_role\s*\(', "Detected IAM role deletion", "high"),

        # Privilege escalation
        (r'sts\.assume_role\s*\(', "Detected role assumption - verify legitimacy", "medium"),
        (r'AdministratorAccess', "Reference to AdministratorAccess policy", "high"),
        (r'PowerUserAccess', "Reference to PowerUserAccess policy", "medium"),
    ]

    # 需要上下文感知的网络安全模式（CIDR）
    network_cidr_patterns = [
        (r'0\.0\.0\.0/0', "0.0.0.0/0"),
        (r'::/0', "::/0"),
    ]

    for pattern, message, severity in dangerous_patterns:
        # 对于一般危险模式，在可执行代码中检测（排除注释）
        if re.search(pattern, executable_code, re.IGNORECASE):
            issues.append({
                "type": "dangerous_operation",
                "message": message,
                "severity": severity
            })
            if severity == "high":
                risk_level = "high"
            elif severity == "medium" and risk_level != "high":
                risk_level = "medium"

    # 对 CIDR 模式进行上下文感知检测
    for pattern, cidr_value in network_cidr_patterns:
        if re.search(pattern, code):
            # 检查是否在安全上下文中
            if not _is_safe_cidr_context(code, cidr_value):
                # 危险：在 authorize 操作中添加开放 CIDR
                issues.append({
                    "type": "dangerous_operation",
                    "message": f"Detected open CIDR block ({cidr_value}) in authorize operation - adding open access",
                    "severity": "high"
                })
                risk_level = "high"
            else:
                # 安全：在 revoke 操作中或只在注释中
                logger.info(f"CIDR {cidr_value} found in safe context (revoke/comment) - no issue raised")

    # === Sensitive Information Detection ===
    sensitive_patterns = [
        # Hardcoded credentials
        (r'password\s*=\s*["\'][^"\']{8,}["\']', "Hardcoded password detected"),
        (r'secret\s*=\s*["\'][^"\']{8,}["\']', "Hardcoded secret detected"),
        (r'api_key\s*=\s*["\'][^"\']{8,}["\']', "Hardcoded API key detected"),
        (r'token\s*=\s*["\'][^"\']{20,}["\']', "Hardcoded token detected"),

        # AWS credentials
        (r'AKIA[0-9A-Z]{16}', "AWS Access Key ID detected in code"),
        (r'["\'][A-Za-z0-9/+=]{40}["\']', "Potential AWS Secret Key detected"),

        # Private keys
        (r'-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----', "Private key detected in code"),
        (r'-----BEGIN\s+EC\s+PRIVATE\s+KEY-----', "EC private key detected in code"),
    ]

    for pattern, message in sensitive_patterns:
        if re.search(pattern, code, re.IGNORECASE):
            issues.append({
                "type": "sensitive_info",
                "message": message,
                "severity": "high"
            })
            risk_level = "high"
            recommendations.append("Remove hardcoded credentials and use AWS Secrets Manager or environment variables")

    # === Code Quality Checks ===
    quality_patterns = [
        # Missing error handling
        (r'except\s*:', "Bare except clause - may catch unexpected errors", "low"),
        (r'pass\s*$', "Empty pass statement in except block", "low"),

        # Unsafe practices
        (r'eval\s*\(', "Use of eval() function - potential code injection", "high"),
        (r'exec\s*\(', "Use of exec() function - potential code injection", "high"),
        (r'subprocess\.call\s*\([^)]*shell\s*=\s*True', "Shell=True in subprocess - command injection risk", "high"),
    ]

    for pattern, message, severity in quality_patterns:
        if re.search(pattern, code, re.MULTILINE):
            issues.append({
                "type": "code_quality",
                "message": message,
                "severity": severity
            })
            if severity == "high":
                risk_level = "high"

    # === Determine final status ===
    high_severity_count = sum(1 for i in issues if i.get("severity") == "high")
    medium_severity_count = sum(1 for i in issues if i.get("severity") == "medium")

    if high_severity_count > 0:
        status = "rejected"
        recommendations.append("Review and fix all high-severity issues before execution")
    elif medium_severity_count > 2:
        status = "warning"
        recommendations.append("Consider reviewing medium-severity issues")
    elif issues:
        status = "warning"
    else:
        status = "passed"
        recommendations.append("Code passed security review")

    result = {
        "status": status,
        "issues": issues,
        "risk_level": risk_level,
        "recommendations": recommendations,
        "summary": {
            "total_issues": len(issues),
            "high_severity": high_severity_count,
            "medium_severity": medium_severity_count,
            "low_severity": sum(1 for i in issues if i.get("severity") == "low")
        }
    }

    logger.info(f"Code review completed: status={status}, risk_level={risk_level}, issues={len(issues)}")
    return result


def _check_email_already_sent(task_id: str, is_rollback: bool, region: str) -> bool:
    """检查邮件是否已发送，防止 Agent 重复调用。

    Args:
        task_id: 任务 ID
        is_rollback: 是否为回滚操作
        region: AWS Region

    Returns:
        bool: True 如果邮件已发送
    """
    tasks_table_name = os.environ.get('TASKS_TABLE')
    if not tasks_table_name:
        logger.warning("TASKS_TABLE not configured, skipping duplicate check")
        return False

    try:
        dynamodb = boto3.resource('dynamodb', region_name=region)
        tasks_table = dynamodb.Table(tasks_table_name)

        response = tasks_table.get_item(
            Key={'PK': f'TASK#{task_id}', 'SK': 'METADATA'},
            ProjectionExpression='resultEmailSent, rollbackEmailSent'
        )

        task = response.get('Item')
        if not task:
            return False

        # 根据操作类型检查对应的邮件发送状态
        if is_rollback:
            return task.get('rollbackEmailSent', False)
        else:
            return task.get('resultEmailSent', False)

    except Exception as e:
        logger.warning(f"Error checking email sent status: {e}")
        return False


@tool
def trigger_result_email(
    task_id: str,
    resource_arn: str,
    control_id: str,
    code_review_result: dict,
    validation_result: dict,
    is_rollback: bool = False,
    rollback_failed: bool = False,
    error_message: Optional[str] = None,
    remediation_type: str = "aws_api",
    pr_info: Optional[dict] = None,
    vulnerabilities: Optional[list] = None
) -> dict:
    """Trigger email service to send result email.

    After Validator completes verification, invoke email service to send
    result email to user.

    For aws_api mode:
    - Code review results
    - Validation results
    - Rollback link (for normal remediation only)

    For github_pr mode:
    - PR information and link
    - Files changed summary
    - Vulnerabilities list (from Memory)
    - Instructions for human review

    Supports two modes:
    - HTTP mode (local): Calls EMAIL_SERVICE_URL (e.g., http://email:8080/send)
    - Lambda mode (AWS): Invokes RESULT_EMAIL_LAMBDA_ARN or APPROVAL_HANDLER_ARN

    NOTE: This tool includes duplicate prevention - if the email was already
    sent for this task (checked via DynamoDB), it returns success without
    invoking Lambda again. This prevents Agent from sending duplicate emails.

    Args:
        task_id: Task ID
        resource_arn: Resource ARN
        control_id: Security Hub Control ID (empty for container CVE)
        code_review_result: Results from review_code_security tool (aws_api mode)
        validation_result: Results from verify_resource_state tool (aws_api mode)
        is_rollback: Whether this is a rollback operation (no rollback link in email)
        rollback_failed: Whether the rollback operation failed
        error_message: Error message to include if operation failed
        remediation_type: Type of remediation ("aws_api" or "github_pr")
        pr_info: Pull Request information (github_pr mode only)
            - pr_number: int - PR number
            - pr_url: str - PR URL
            - title: str - PR title
            - state: str - PR state
        vulnerabilities: Vulnerability list (github_pr mode only, from Memory)
            - cve_id: str - CVE identifier
            - severity: str - CRITICAL/HIGH
            - package_name: str - Affected package
            - installed_version: str - Current version
            - fixed_version: str - Fixed version

    Returns:
        dict: Email trigger result including:
            - success: bool - Whether email service was invoked successfully
            - sent: bool - Whether email will be sent
            - includes_rollback_link: bool - Whether email has rollback link (aws_api)
            - includes_pr_link: bool - Whether email has PR link (github_pr)
            - error: str - Error message if failed
            - already_sent: bool - True if email was already sent (duplicate prevented)
    """
    config = get_config()

    # ===== 防重复检查：在 Agent 端防止重复调用 Lambda =====
    if _check_email_already_sent(task_id, is_rollback, config.region):
        email_type_desc = "rollback" if is_rollback else "remediation result"
        logger.warning(f"Email already sent for task {task_id} ({email_type_desc}), skipping duplicate")
        return {
            "success": True,
            "sent": False,
            "already_sent": True,
            "includes_rollback_link": not is_rollback and remediation_type == "aws_api",
            "includes_pr_link": remediation_type == "github_pr",
            "email_type": "rollback_success" if is_rollback else "remediation_result",
            "message": f"邮件已发送，跳过重复调用 (task_id={task_id})"
        }

    # Determine email type and content
    if remediation_type == "github_pr":
        # GitHub PR mode - send PR result email
        email_type = "github_pr_result"
        include_rollback_link = False
        include_pr_link = True

        # Normalize pr_info field names (GitHub API returns 'number'/'url', we expect 'pr_number'/'pr_url')
        normalized_pr_info = {}
        if pr_info:
            normalized_pr_info = {
                "pr_number": pr_info.get("pr_number") or pr_info.get("number"),
                "pr_url": pr_info.get("pr_url") or pr_info.get("url"),
                "title": pr_info.get("title", ""),
                "state": pr_info.get("state", "open"),
                "branch_name": pr_info.get("branch_name") or pr_info.get("head_branch", ""),
                "files_changed": pr_info.get("files_changed", [])
            }

        # Build PR email payload
        payload = {
            "action": "send_result_email",
            "task_id": task_id,
            "resource_arn": resource_arn,
            "control_id": control_id or "",
            "email_type": email_type,
            "remediation_type": "github_pr",
            "pr_info": normalized_pr_info,
            "vulnerabilities": vulnerabilities or [],  # 漏洞列表从 Memory 获取
            "validation": {
                "pr_verified": validation_result.get("pr_verified", False),
                "files_verified": validation_result.get("files_verified", False),
                "summary": validation_result.get("summary", "")
            },
            "include_pr_link": include_pr_link,
            "error_message": error_message
        }
    else:
        # AWS API mode - original logic
        if is_rollback:
            if rollback_failed:
                email_type = "rollback_failed"
            else:
                email_type = "rollback_success"
            include_rollback_link = False
        else:
            email_type = "remediation_result"
            include_rollback_link = True
        include_pr_link = False

        # Build email payload
        # 提取检查明细供邮件显示
        code_issues = code_review_result.get("issues", [])
        validation_checks = validation_result.get("checks", [])

        payload = {
            "action": "send_result_email",
            "task_id": task_id,
            "resource_arn": resource_arn,
            "control_id": control_id,
            "email_type": email_type,
            "remediation_type": "aws_api",
            "code_review": {
                "status": code_review_result.get("status", "unknown"),
                "issues_count": code_review_result.get("summary", {}).get("total_issues", 0),
                "risk_level": code_review_result.get("risk_level", "unknown"),
                "issues": code_issues,  # 传递完整的问题列表
                "recommendations": code_review_result.get("recommendations", [])
            },
            "validation": {
                "passed": validation_result.get("passed", False),
                "checks_count": len(validation_checks),
                "checks": validation_checks,  # 传递完整的检查项列表
                "summary": validation_result.get("summary", "")
            },
            "include_rollback_link": include_rollback_link,
            "is_rollback": is_rollback,
            "rollback_failed": rollback_failed,
            "error_message": error_message
        }

    logger.info(f"Triggering result email for task {task_id}")
    logger.info(f"Email type: {email_type}, remediation_type: {remediation_type}")

    # 获取 Lambda ARN（通过 approval-handler Lambda 发邮件）
    approval_handler_arn = os.environ.get('APPROVAL_HANDLER_ARN')

    if not approval_handler_arn:
        logger.warning("APPROVAL_HANDLER_ARN 未配置")
        return {
            "success": True,
            "sent": False,
            "includes_rollback_link": include_rollback_link if remediation_type == "aws_api" else False,
            "includes_pr_link": include_pr_link if remediation_type == "github_pr" else False,
            "email_type": email_type,
            "message": "邮件 Lambda 未配置（测试环境预期行为）"
        }

    return _send_email_lambda(
        approval_handler_arn, payload, config.region,
        include_rollback_link if remediation_type == "aws_api" else False,
        include_pr_link if remediation_type == "github_pr" else False,
        email_type
    )


def _send_email_lambda(
    lambda_arn: str,
    payload: dict,
    region: str,
    include_rollback_link: bool,
    include_pr_link: bool,
    email_type: str
) -> dict:
    """通过 Lambda 发送邮件（AWS 部署模式）"""
    try:
        lambda_client = boto3.client('lambda', region_name=region)

        response = lambda_client.invoke(
            FunctionName=lambda_arn,
            InvocationType='Event',  # Async invocation
            Payload=json.dumps(payload)
        )

        status_code = response.get('StatusCode', 0)
        success = status_code in [200, 202]

        logger.info(f"Lambda invocation response: StatusCode={status_code}")

        return {
            "success": success,
            "sent": success,
            "includes_rollback_link": include_rollback_link,
            "includes_pr_link": include_pr_link,
            "email_type": email_type,
            "lambda_status_code": status_code
        }

    except ClientError as e:
        logger.error(f"Failed to invoke result email Lambda: {e}")
        return {
            "success": False,
            "error": f"Lambda invocation failed: {str(e)}"
        }

    except Exception as e:
        logger.exception(f"Error triggering result email: {e}")
        return {
            "success": False,
            "error": f"Failed to trigger result email: {str(e)}"
        }
